PLUGINNAME = ReplaceCPUPlugin
PLUGINOBJECTS =  $(PLUGINNAME).o ofxsLut.o ofxsRectangleInteract.o
RESOURCES = OpenFX.Yo.ReplaceCPU.png
ENABLEGPU := FALSE

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
