PLUGINNAME = ScanCPUPlugin
PLUGINOBJECTS = $(PLUGINNAME).o ofxsLut.o ofxsRectangleInteract.o
RESOURCES = OpenFX.Yo.ScanCPU.png
ENABLEGPU := FALSE

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
