PLUGINNAME = BalancePlugin
PLUGINOBJECTS = $(PLUGINNAME).o ofxsLut.o ofxsRectangleInteract.o $(PLUGINNAME)CudaKernel.o $(PLUGINNAME)OpenCLKernel.o
RESOURCES = OpenFX.Yo.Balance.png
ENABLEGPU := TRUE
CUDALIB = lib7.5

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
