PLUGINNAME = ReplacePlugin
PLUGINOBJECTS =  $(PLUGINNAME).o ofxsLut.o ofxsRectangleInteract.o $(PLUGINNAME)CudaKernel.o $(PLUGINNAME)OpenCLKernel.o
RESOURCES = OpenFX.Yo.Replace.png
ENABLEGPU := TRUE

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
